### ISSUE TITLE
Último merge não foi aceito: #65 from LABHDUFBA/thibau

### ISSUE THREAD

**Issue by l-thibau** [LABHDUFBA/labhdufba.github.io#66]
Precisamos verificar o porquê dessa mensagem de erro. 

![Image](https://github.com/user-attachments/assets/ecc09eba-7457-4f4c-8908-ddf940754764)

**Comment by ericbrasiln** [comment]
o erro está no yml do deploy: https://github.com/LABHDUFBA/labhdufba.github.io/blob/16e51198ec2f4a0255d9c3f4f14e352b8e5619f8/.github/workflows/hugo.yaml

Vou corrigir e te marco para revisão.

**Comment by ericbrasiln** [comment]
@l-thibau 

Passei o yml e o erro para o copilot do próprio Github e essa foi a resposta:

---

Parece que a falha ocorreu durante a execução do job de deploy. Aqui estão algumas sugestões para corrigir o problema:

1. **Verifique se o GitHub Pages está habilitado**:
   - Certifique-se de que o GitHub Pages está habilitado nas configurações do repositório em [https://github.com/LABHDUFBA/labhdufba.github.io/settings/pages](https://github.com/LABHDUFBA/labhdufba.github.io/settings/pages).

2. **Atualize a versão da ação `deploy-pages`**:
   - Certifique-se de estar usando a versão mais recente da ação `deploy-pages`. A versão atual é `v3`, mas pode haver atualizações ou patches disponíveis.

3. **Adicione logs de depuração**:
   - Adicione logs de depuração para entender melhor o motivo pelo qual a URL do artefato não está sendo recuperada corretamente:
     ```yaml
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v3
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
       env:
         DEBUG: true
     ```

4. **Verifique o upload do artefato**:
   - Certifique-se de que o passo de upload do artefato está configurado corretamente e que o caminho está correto:
     ```yaml
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         path: ./public
     ```

Aqui está o arquivo `yaml` atualizado com as alterações sugeridas:

```yaml
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.7
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: true
```

Tente aplicar essas alterações e execute novamente o workflow para ver se o problema foi resolvido.
